model_name: PDFMetadata
description: Metadata of a scientific paper
columns:
  - name: title
    type: str
  - name: authors
    type: list[str]
  - name: year
    type: int
  - name: publisher
    type: str | None
  - name: summary
    type: str | None